name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo DATABASE_URL=postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@better-up-postgres:5432/postgres > .env
            echo -e "GITHUB_ID=${{ secrets.GIT_ID }}\nGITHUB_SECRET=${{ secrets.GIT_SECRET }}\nNEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}\nNEXTAUTH_DEBUG=false"\nNEXTAUTH_URL="http://50.16.33.174:3000" > .env.local
            


            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/better-up-turbo:linux
            sudo docker network create better-up || true
            sudo docker volume create pgdata || true

            sudo docker rm -f better-up-postgres || true
            sudo docker rm -f better-up-redis || true
            sudo docker rm -f better-up-turbo || true

            sudo docker run -d \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              --name better-up-postgres \
              --network better-up \
              -v pgdata:/var/lib/postgresql/data \
              postgres
            

            sudo docker run -d \
              --name better-up-redis \
              --network better-up \
              redis

            sudo docker run -d -p 3000:3000 -p 3001:3001 \
              --name better-up-turbo \
              --network better-up \
              -v /home/ubuntu/.env:/nextApp/packages/db/.env \
              -v /home/ubuntu/.env.local:/nextApp/apps/my-app/.env.local \
              -e PRISMA_ENV_PATH=/nextApp/packages/db/.env \
              ${{ secrets.DOCKER_USERNAME }}/better-up-turbo:linux


      


