name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/better-up-turbo:linux
            docker network create better-up || true
            docker volume create pgdata || true

            docker rm -f better-up-postgres || true
            docker rm -f better-up-turbo || true

            docker run -d \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              --name better-up-postgres \
              --network better-up \
              -v pgdata:/var/lib/postgresql/data \
              postgres

            docker run -d -p 3000:3000 -p 3001:3001 \
            --name better-up-turbo \
            --network better-up \
            ${{ secrets.DOCKER_USERNAME }}/better-up-turbo:linux

      


