name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-turborepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: push Docker build
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKER_USERNAME }}/better-up-turbo:linux .
      



  
